### ISSUE TITLE
Multi line comments

### ISSUE THREAD

**Issue by psulat** [evanw/glslx#2]
Multi-line comments such as:

/\* 
This is a comment
*/

are not parsed correctly.  All comments must be on one line.  Not a show stopper but users should be aware of this limitation.   

Evan,

Thanks for making this available!  On a side note, I was disappointed to see Figma pivot. I was looking forward to what kind of image editor you would come up with.  Photoshop, with its featuritis, is ripe to be taken down a peg or two.

Pete

**Comment by evanw** [comment]
Oh crap, I bet you're on Windows. It looks like I didn't test it for \r\n, only for \n. The latest version should fix that.

Figma is a creative tools company and we plan to ultimately build lots of creative tools, but we need to build the business first so Figma has a solid foundation. It turned out that a screen design tool was a better market opportunity for us than an image editor. I built some really awesome image editing tech internally and I was really looking forward to sharing it with the world, so I know how you feel! A lot of us at Figma want to do an image editor too so hopefully that'll be our next tool. That's a ways off at the moment though.
